version: '3'

services:
  backend:
    build: .
    expose:
      - 5000
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=UCal
    volumes:
      - ./UCal:/server

  frontend:
    build: ./app
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./app:/app