"""empty message

Revision ID: 620daf2877dd
Revises: ef945e61ef8b
Create Date: 2019-12-02 11:40:14.854148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620daf2877dd'
down_revision = 'ef945e61ef8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('course', sa.String(length=64), nullable=True))
    op.add_column('events', sa.Column('frequencyType', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('guests', sa.String(), nullable=True))
    op.add_column('users', sa.Column('courses', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'courses')
    op.drop_column('events', 'guests')
    op.drop_column('events', 'frequencyType')
    op.drop_column('events', 'course')
    # ### end Alembic commands ###
