"""added course column

Revision ID: 708014887a6e
Revises: d99cca362920
Create Date: 2019-11-28 05:57:50.395059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708014887a6e'
down_revision = 'd99cca362920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('course', sa.String(length=64), nullable=True))
    # op.add_column('users', sa.Column('courses', sa.ARRAY(sa.String(length=64)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('users', 'courses')
    op.drop_column('events', 'course')
    # ### end Alembic commands ###
