"""empty message

Revision ID: 9a43fb52c21a
Revises: e6918c670ac0
Create Date: 2019-12-04 00:49:34.489425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a43fb52c21a'
down_revision = 'e6918c670ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notifications', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notifications')
    # ### end Alembic commands ###
