"""empty message

Revision ID: e6918c670ac0
Revises: 620daf2877dd
Create Date: 2019-12-04 00:48:11.634657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6918c670ac0'
down_revision = '620daf2877dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notifications', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notifications')
    # ### end Alembic commands ###
