"""Adds frequency type for Event model

Revision ID: ef945e61ef8b
Revises: 2815c7546c18
Create Date: 2019-11-29 15:02:31.681212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef945e61ef8b'
down_revision = '2815c7546c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('frequencyType', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'frequencyType')
    # ### end Alembic commands ###
