"""empty message

Revision ID: f40943a6d424
Revises: 092e54475f55
Create Date: 2019-11-28 08:08:36.025604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40943a6d424'
down_revision = '092e54475f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('courses', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'courses')
    # ### end Alembic commands ###
